# Generated by Django 4.1.5 on 2023-02-19 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiplefiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="files",
            field=models.FileField(
                upload_to="files__",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
